name: "Golang CI"
description: "Checkout, setup Go, test, and build"
inputs:
  token:
    required: true
    description: "GitHub token for private repo"
runs:
  using: "composite"
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: 1.27.x

    - name: Config private repository
      shell: bash
      run: |
        git config --global url."https://${{ inputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Test Golang Code
      shell: bash
      run: go test -v ./...

    - name: Build
      shell: bash
      run: GOOS=linux go build -o ./out/goapp ./cmd/api/main.go
